#DAY 36 :Exception Handling in Python

